"""add workflow criteria fields to stories

Revision ID: 1970463ad067
Revises: change_assignee_to_assignees
Create Date: 2025-12-06 19:31:16.830948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1970463ad067'
down_revision: Union[str, Sequence[str], None] = 'change_assignee_to_assignees'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stories', sa.Column('bv', sa.Integer(), nullable=True))
    op.add_column('stories', sa.Column('refinement_session_scheduled', sa.Boolean(), nullable=True))
    op.add_column('stories', sa.Column('groomed', sa.Boolean(), nullable=True))
    op.add_column('stories', sa.Column('dependencies', sa.JSON(), nullable=True))
    op.add_column('stories', sa.Column('session_documented', sa.Boolean(), nullable=True))
    op.add_column('stories', sa.Column('refinement_dependencies', sa.JSON(), nullable=True))
    op.add_column('stories', sa.Column('team_approval', sa.Boolean(), nullable=True))
    op.add_column('stories', sa.Column('po_approval', sa.Boolean(), nullable=True))
    op.add_column('stories', sa.Column('sprint_capacity', sa.Integer(), nullable=True))
    op.add_column('stories', sa.Column('skills_available', sa.Boolean(), nullable=True))
    op.add_column('stories', sa.Column('team_commits', sa.Boolean(), nullable=True))
    op.add_column('stories', sa.Column('tasks_identified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stories', 'tasks_identified')
    op.drop_column('stories', 'team_commits')
    op.drop_column('stories', 'skills_available')
    op.drop_column('stories', 'sprint_capacity')
    op.drop_column('stories', 'po_approval')
    op.drop_column('stories', 'team_approval')
    op.drop_column('stories', 'refinement_dependencies')
    op.drop_column('stories', 'session_documented')
    op.drop_column('stories', 'dependencies')
    op.drop_column('stories', 'groomed')
    op.drop_column('stories', 'refinement_session_scheduled')
    op.drop_column('stories', 'bv')
    # ### end Alembic commands ###
